config setup
    uniqueids=no

conn lab
    keyexchange=ikev2
    type=tunnel
    authby=psk
    left=172.30.0.2
    leftid=@left
    leftsubnet=10.10.0.1/32
    right=172.30.0.3
    rightid=@right
    rightsubnet=10.20.0.1/32
    ike=aes256gcm16-prfsha256-ecp256!
    esp=aes256gcm16!
    mobike=no
    forceencaps=yes
    rekey=no
    reauth=no
    dpdaction=none
    auto=add
