config setup
    uniqueids=no

conn lab
    keyexchange=ikev1
    aggressive=no
    type=tunnel
    authby=psk
    left=172.30.0.2
    leftid=@left
    leftsubnet=10.10.0.1/32
    right=172.30.0.3
    rightid=@right
    rightsubnet=10.20.0.1/32
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256-modp2048!
    forceencaps=no
    rekey=no
    dpdaction=none
    auto=add
