config setup
    uniqueids=no

conn lab
    keyexchange=ikev2
    type=tunnel
    authby=psk
    left=fd00:30::2
    leftid=@left
    leftsubnet=fd10::1/128
    right=fd00:30::3
    rightid=@right
    rightsubnet=fd20::1/128
    ike=aes256-sha384-ecp384!
    esp=aes256-sha384!
    mobike=no
    forceencaps=no
    rekey=no
    reauth=no
    dpdaction=none
    auto=add
